#ifndef BUFFERATTRIBUTE_H
#define BUFFERATTRIBUTE_H

enum BufferAttribute {
    VERTEX_BUFFER,
    COLOUR_BUFFER,
    NORMAL_BUFFER,
    INDEX_BUFFER,
    TEXTURE_BUFFER,
    BUFFER_COUNT,
};

#endif 